export enum Phase {
  BACKLOG = 'backlog',
  SEED_INITIAL_DISCUSS = 'seed-initial-discuss',
  DISCOVERY_BRAINSTORM = 'discovery-brainstorm',
  HYPOTHESIS_OPTIONS = 'hypothesis-options',
  SPECS_SOLUTIONING = 'specs-solutioning',
  DECISION = 'decision',
  TASK_EXECUTION = 'task-execution',
  DOCUMENTATION_NARR = 'documentation-narrative',
  RETRO_LEARNING = 'retro-learning',
}

export enum RoleType {
  FEATURE = 'feature',
  BUG = 'bug',
  QUESTION = 'question',
  CLAIM = 'claim',
  COUNTER_CLAIM = 'counter-claim',
  EVIDENCE = 'evidence',
  RISK = 'risk',
  MITIGATION = 'mitigation',
  ASSUMPTION = 'assumption',
  DECISION_RATIONALE = 'decision-rationale',
  CUSTOMER_VOICE = 'customer-voice',
  DESIGN_ARTIFACT = 'design-artifact',
  EXPERIMENT = 'experiment',
  BLOCKER = 'blocker',
  DEPENDENCY = 'dependency',
  STATUS_UPDATE = 'status-update',
}
